"""add_budget_rate_overrides

Revision ID: 288c3cba972d
Revises: 423d9090d576
Create Date: 2026-04-14 00:18:22.918882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288c3cba972d'
down_revision: Union[str, None] = '423d9090d576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('manual_tc_multiplier_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('automation_tc_multiplier_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('adhoc_request_multiplier_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('working_days_per_week_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('hrs_per_wk_per_hc_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('manual_hc_divisor_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('automation_hc_divisor_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('hc_rate_card_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('sqpm_boise_pct_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('pl_pct_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('per_wqe_pct_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('asqpm_pct_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('lab_tech_manager_pct_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('project_manager_pct_override', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'project_manager_pct_override')
    op.drop_column('budgets', 'lab_tech_manager_pct_override')
    op.drop_column('budgets', 'asqpm_pct_override')
    op.drop_column('budgets', 'per_wqe_pct_override')
    op.drop_column('budgets', 'pl_pct_override')
    op.drop_column('budgets', 'sqpm_boise_pct_override')
    op.drop_column('budgets', 'hc_rate_card_override')
    op.drop_column('budgets', 'automation_hc_divisor_override')
    op.drop_column('budgets', 'manual_hc_divisor_override')
    op.drop_column('budgets', 'hrs_per_wk_per_hc_override')
    op.drop_column('budgets', 'working_days_per_week_override')
    op.drop_column('budgets', 'adhoc_request_multiplier_override')
    op.drop_column('budgets', 'automation_tc_multiplier_override')
    op.drop_column('budgets', 'manual_tc_multiplier_override')
    # ### end Alembic commands ###
