"""normalize_dates_and_holidays

Revision ID: 2d35636aa134
Revises: aee5de350a60
Create Date: 2026-04-15 21:51:55.734133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d35636aa134'
down_revision: Union[str, None] = 'aee5de350a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_holidays', sa.Column('business_unit', sa.String(length=128), nullable=True))
    op.drop_index('ix_company_holidays_holiday_date', table_name='company_holidays')
    op.create_index(op.f('ix_company_holidays_holiday_date'), 'company_holidays', ['holiday_date'], unique=False)
    op.add_column('test_runs', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_runs', 'start_date')
    op.drop_index(op.f('ix_company_holidays_holiday_date'), table_name='company_holidays')
    op.create_index('ix_company_holidays_holiday_date', 'company_holidays', ['holiday_date'], unique=True)
    op.drop_column('company_holidays', 'business_unit')
    # ### end Alembic commands ###
