"""Add company holidays

Revision ID: 35b8bda1f859
Revises: 9c4d22c0f67c
Create Date: 2026-04-15 01:24:37.607676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b8bda1f859'
down_revision: Union[str, None] = '9c4d22c0f67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_holidays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_holidays_holiday_date'), 'company_holidays', ['holiday_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_holidays_holiday_date'), table_name='company_holidays')
    op.drop_table('company_holidays')
    # ### end Alembic commands ###
