"""add_soft_delete_and_lock_fields

Revision ID: 423d9090d576
Revises: a680436f2106
Create Date: 2026-04-14 00:03:12.612296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423d9090d576'
down_revision: Union[str, None] = 'a680436f2106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('budgets', sa.Column('is_locked', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('sub_divisions', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_divisions', 'is_deleted')
    op.drop_column('projects', 'is_deleted')
    op.drop_column('budgets', 'is_locked')
    op.drop_column('budgets', 'is_deleted')
    # ### end Alembic commands ###
