"""Add direct and indirect HC costs

Revision ID: 429e5dadf6fc
Revises: a1b2c3d4e5f6
Create Date: 2026-04-21 04:41:28.162958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429e5dadf6fc'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('direct_hc_cost', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('indirect_hc_cost', sa.Float(), nullable=True))
    op.drop_index('ix_test_runs_end_date', table_name='runs')
    op.drop_index('ix_test_runs_status', table_name='runs')
    op.create_index(op.f('ix_runs_end_date'), 'runs', ['end_date'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.drop_index('ix_sub_divisions_end_date', table_name='teams')
    op.create_index(op.f('ix_teams_end_date'), 'teams', ['end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_end_date'), table_name='teams')
    op.create_index('ix_sub_divisions_end_date', 'teams', ['end_date'], unique=False)
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_end_date'), table_name='runs')
    op.create_index('ix_test_runs_status', 'runs', ['status'], unique=False)
    op.create_index('ix_test_runs_end_date', 'runs', ['end_date'], unique=False)
    op.drop_column('budgets', 'indirect_hc_cost')
    op.drop_column('budgets', 'direct_hc_cost')
    # ### end Alembic commands ###
