"""Refactor to 5-layer hierarchy

Revision ID: 4369c86eb660
Revises: 288c3cba972d
Create Date: 2026-04-14 23:43:04.500742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4369c86eb660'
down_revision: Union[str, None] = '288c3cba972d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sub_division_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sub_division_id'], ['sub_divisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_sub_division_id'), 'test_runs', ['sub_division_id'], unique=False)
    op.add_column('budgets', sa.Column('test_run_id', sa.UUID(), nullable=False))
    op.drop_index('ix_budgets_sub_division_id', table_name='budgets')
    op.create_index(op.f('ix_budgets_test_run_id'), 'budgets', ['test_run_id'], unique=True)
    op.drop_constraint('budgets_sub_division_id_fkey', 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'test_runs', ['test_run_id'], ['id'], ondelete='CASCADE')
    op.drop_column('budgets', 'sub_division_id')
    op.add_column('projects', sa.Column('business_unit', sa.String(length=128), server_default='Default', nullable=False))
    op.create_index(op.f('ix_projects_business_unit'), 'projects', ['business_unit'], unique=False)
    op.drop_constraint('uq_subdivision_project_name', 'sub_divisions', type_='unique')
    op.create_index('uq_subdivision_project_name', 'sub_divisions', ['project_id', 'name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_subdivision_project_name', table_name='sub_divisions', postgresql_where=sa.text('is_deleted = false'))
    op.create_unique_constraint('uq_subdivision_project_name', 'sub_divisions', ['project_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_projects_business_unit'), table_name='projects')
    op.drop_column('projects', 'business_unit')
    op.add_column('budgets', sa.Column('sub_division_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.create_foreign_key('budgets_sub_division_id_fkey', 'budgets', 'sub_divisions', ['sub_division_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_budgets_test_run_id'), table_name='budgets')
    op.create_index('ix_budgets_sub_division_id', 'budgets', ['sub_division_id'], unique=True)
    op.drop_column('budgets', 'test_run_id')
    op.drop_index(op.f('ix_test_runs_sub_division_id'), table_name='test_runs')
    op.drop_table('test_runs')
    # ### end Alembic commands ###
