"""add_admin_action_logs

Revision ID: 533110036423
Revises: 743869022632
Create Date: 2026-04-27 00:57:53.047716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '533110036423'
down_revision: Union[str, None] = '743869022632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=64), nullable=True, comment='Denormalized admin username at time of action'),
    sa.Column('action', sa.Enum('USER_PROVISION', 'USER_UPDATE', 'USER_DELETE', 'USER_ACTIVATE', 'USER_DEACTIVATE', 'USER_PASSWORD_RESET', name='admin_action_type'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True, comment='UUID of the affected user (or entity)'),
    sa.Column('target_name', sa.String(length=64), nullable=True, comment='Denormalized target username at time of action'),
    sa.Column('detail', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Structured details e.g. {old_role: false, new_role: true}'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_action_logs_action'), 'admin_action_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_actor_id'), 'admin_action_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_target_id'), 'admin_action_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_timestamp'), 'admin_action_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_action_logs_timestamp'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_target_id'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_actor_id'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_action'), table_name='admin_action_logs')
    op.drop_table('admin_action_logs')
    # ### end Alembic commands ###
