"""make_project_name_composite_unique

Revision ID: 5b28fb0a0dee
Revises: 2d35636aa134
Create Date: 2026-04-16 01:20:13.747317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b28fb0a0dee'
down_revision: Union[str, None] = '2d35636aa134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_name', table_name='projects')
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_unique_constraint('uix_projects_bu_name', 'projects', ['business_unit', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_projects_bu_name', 'projects', type_='unique')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.create_index('ix_projects_name', 'projects', ['name'], unique=True)
    # ### end Alembic commands ###
