"""Split hc_rate_card_override into role-specific fields

Revision ID: 6a20c6f137cc
Revises: 35b8bda1f859
Create Date: 2026-04-15 01:41:22.471792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a20c6f137cc'
down_revision: Union[str, None] = '35b8bda1f859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('manual_hourly_rate_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('automation_hourly_rate_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('asqpm_hourly_rate_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('lead_hourly_rate_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('pm_hourly_rate_override', sa.Float(), nullable=True))
    op.drop_column('budgets', 'hc_rate_card_override')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('hc_rate_card_override', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('budgets', 'pm_hourly_rate_override')
    op.drop_column('budgets', 'lead_hourly_rate_override')
    op.drop_column('budgets', 'asqpm_hourly_rate_override')
    op.drop_column('budgets', 'automation_hourly_rate_override')
    op.drop_column('budgets', 'manual_hourly_rate_override')
    # ### end Alembic commands ###
