"""add_username_to_audit_logs

Revision ID: 743869022632
Revises: 759e8ab81c8c
Create Date: 2026-04-27 00:43:49.462319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743869022632'
down_revision: Union[str, None] = '759e8ab81c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('username', sa.String(length=64), nullable=True, comment='Denormalized username for quick log readability'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'username')
    # ### end Alembic commands ###
