"""Add Business Unit

Revision ID: 759e8ab81c8c
Revises: 429e5dadf6fc
Create Date: 2026-04-22 01:42:53.762692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759e8ab81c8c'
down_revision: Union[str, None] = '429e5dadf6fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create `business_units` table
    op.create_table('business_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_units_name'), 'business_units', ['name'], unique=True)

    # 2. Add nullable foreign keys
    op.add_column('company_holidays', sa.Column('business_unit_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_company_holidays_business_unit_id'), 'company_holidays', ['business_unit_id'], unique=False)
    # We delay creating foreign key to company_holidays down below, or we can just do it since it's nullable
    op.add_column('families', sa.Column('business_unit_id', sa.UUID(), nullable=True))
    
    # 3. Data Migration
    conn = op.get_bind()
    # Extract unique BUs from families
    results = conn.execute(sa.text('SELECT DISTINCT business_unit FROM families')).fetchall()
    
    import uuid
    bu_map = {}
    for row in results:
        bu_name = row[0]
        new_id = uuid.uuid4()
        bu_map[bu_name] = new_id
        # Insert into business_units
        conn.execute(sa.text(
            'INSERT INTO business_units (id, name, is_deleted) VALUES (:id, :name, false)'
        ).bindparams(id=new_id, name=bu_name))
        
    # Extra check for company_holidays string column
    results_ch = conn.execute(sa.text('SELECT DISTINCT business_unit FROM company_holidays WHERE business_unit IS NOT NULL')).fetchall()
    for row in results_ch:
        bu_name = row[0]
        if bu_name not in bu_map:
            new_id = uuid.uuid4()
            bu_map[bu_name] = new_id
            conn.execute(sa.text(
                'INSERT INTO business_units (id, name, is_deleted) VALUES (:id, :name, false)'
            ).bindparams(id=new_id, name=bu_name))

    # Update families and company_holidays
    for bu_name, bu_id in bu_map.items():
        conn.execute(sa.text(
            'UPDATE families SET business_unit_id = :bu_id WHERE business_unit = :bu_name'
        ).bindparams(bu_id=bu_id, bu_name=bu_name))
        conn.execute(sa.text(
            'UPDATE company_holidays SET business_unit_id = :bu_id WHERE business_unit = :bu_name'
        ).bindparams(bu_id=bu_id, bu_name=bu_name))

    # If there were any families with NULL, let's create a 'Default'
    # Actually, the string column `business_unit` was NOT NULL, so families all have it.
    
    # 4. Enforce NOT NULL and constraints
    op.alter_column('families', 'business_unit_id', existing_type=sa.UUID(), nullable=False)
    
    op.create_foreign_key('fk_company_holidays_bu_id', 'company_holidays', 'business_units', ['business_unit_id'], ['id'], ondelete='CASCADE')
    op.drop_column('company_holidays', 'business_unit')
    
    op.drop_index('ix_families_business_unit', table_name='families')
    op.drop_constraint('uix_families_bu_name', 'families', type_='unique')
    op.create_unique_constraint('uix_families_bu_name', 'families', ['business_unit_id', 'name'])
    op.create_index(op.f('ix_families_business_unit_id'), 'families', ['business_unit_id'], unique=False)
    op.create_foreign_key('fk_families_bu_id', 'families', 'business_units', ['business_unit_id'], ['id'], ondelete='CASCADE')
    op.drop_column('families', 'business_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('business_unit', sa.VARCHAR(length=128), server_default=sa.text("'Default'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'families', type_='foreignkey')
    op.drop_index(op.f('ix_families_business_unit_id'), table_name='families')
    op.drop_constraint('uix_families_bu_name', 'families', type_='unique')
    op.create_unique_constraint('uix_families_bu_name', 'families', ['business_unit', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_families_business_unit', 'families', ['business_unit'], unique=False)
    op.drop_column('families', 'business_unit_id')
    op.add_column('company_holidays', sa.Column('business_unit', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'company_holidays', type_='foreignkey')
    op.drop_index(op.f('ix_company_holidays_business_unit_id'), table_name='company_holidays')
    op.drop_column('company_holidays', 'business_unit_id')
    op.drop_index(op.f('ix_business_units_name'), table_name='business_units')
    op.drop_table('business_units')
    # ### end Alembic commands ###
