"""update uq_run_team_name to allow multiple non-active runs with same name

Revision ID: 97041e9fa1a0
Revises: ec8122769434
Create Date: 2026-05-05 18:25:49.052184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97041e9fa1a0'
down_revision: Union[str, None] = 'ec8122769434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teams_name_key', 'teams', type_='unique')
    
    # Manually drop and recreate the uq_run_team_name index to update the where clause
    op.drop_index('uq_run_team_name', table_name='runs')
    op.create_index('uq_run_team_name', 'runs', ['team_id', 'name'], unique=True, postgresql_where=sa.text("is_deleted = false AND status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_run_team_name', table_name='runs')
    op.create_index('uq_run_team_name', 'runs', ['team_id', 'name'], unique=True, postgresql_where=sa.text('is_deleted = false'))

    op.create_unique_constraint('teams_name_key', 'teams', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
