"""Add indexes to budget filtering fields

Revision ID: 9c4d22c0f67c
Revises: 4369c86eb660
Create Date: 2026-04-15 00:42:49.256246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c4d22c0f67c'
down_revision: Union[str, None] = '4369c86eb660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_budgets_is_locked'), 'budgets', ['is_locked'], unique=False)
    op.create_index(op.f('ix_budgets_manual_hc'), 'budgets', ['manual_hc'], unique=False)
    op.create_index(op.f('ix_budgets_total_budget'), 'budgets', ['total_budget'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budgets_total_budget'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_manual_hc'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_is_locked'), table_name='budgets')
    # ### end Alembic commands ###
