"""initial_schema

Revision ID: a4557317174f
Revises: 
Create Date: 2026-04-09 23:48:24.749053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4557317174f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='project_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_table('rate_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_cards_key_name'), 'rate_cards', ['key_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_password_change', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False, comment="SQLAlchemy model class name, e.g. 'Budget', 'RateCard'"),
    sa.Column('entity_id', sa.String(length=64), nullable=False, comment='String-serialised primary key of the affected row'),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='audit_action'), nullable=False),
    sa.Column('old_value', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('auth_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('LOGIN_SUCCESS', 'LOGIN_FAILED', 'PASSWORD_CHANGED', 'MFA_ENABLED', 'TOKEN_INVALIDATED', name='auth_event_type'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_logs_timestamp'), 'auth_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_auth_logs_user_id'), 'auth_logs', ['user_id'], unique=False)
    op.create_table('consumed_totp_codes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumed_totp_codes_expires_at'), 'consumed_totp_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_consumed_totp_codes_user_id'), 'consumed_totp_codes', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('sub_divisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='sub_division_status'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_subdivision_project_name')
    )
    op.create_index(op.f('ix_sub_divisions_end_date'), 'sub_divisions', ['end_date'], unique=False)
    op.create_index(op.f('ix_sub_divisions_project_id'), 'sub_divisions', ['project_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sub_division_id', sa.UUID(), nullable=False),
    sa.Column('tc_count', sa.Integer(), nullable=False),
    sa.Column('duration_in_days', sa.Integer(), nullable=False),
    sa.Column('manual_tc_count', sa.Float(), nullable=True),
    sa.Column('automation_tc_count', sa.Float(), nullable=True),
    sa.Column('adhoc_request', sa.Float(), nullable=True),
    sa.Column('total_tc', sa.Float(), nullable=True),
    sa.Column('duration_wks', sa.Float(), nullable=True),
    sa.Column('manual_hc', sa.Float(), nullable=True),
    sa.Column('automation_hc', sa.Float(), nullable=True),
    sa.Column('manual_hc_cost', sa.Float(), nullable=True),
    sa.Column('automation_hc_cost', sa.Float(), nullable=True),
    sa.Column('lead_cost', sa.Float(), nullable=True),
    sa.Column('sqpm_cost_boise', sa.Float(), nullable=True),
    sa.Column('pl_cost', sa.Float(), nullable=True),
    sa.Column('per_wqe_cost', sa.Float(), nullable=True),
    sa.Column('asqpm_cost', sa.Float(), nullable=True),
    sa.Column('lab_tech_manager_cost', sa.Float(), nullable=True),
    sa.Column('project_manager_cost', sa.Float(), nullable=True),
    sa.Column('total_budget', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sub_division_id'], ['sub_divisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_sub_division_id'), 'budgets', ['sub_division_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budgets_sub_division_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_sub_divisions_project_id'), table_name='sub_divisions')
    op.drop_index(op.f('ix_sub_divisions_end_date'), table_name='sub_divisions')
    op.drop_table('sub_divisions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_consumed_totp_codes_user_id'), table_name='consumed_totp_codes')
    op.drop_index(op.f('ix_consumed_totp_codes_expires_at'), table_name='consumed_totp_codes')
    op.drop_table('consumed_totp_codes')
    op.drop_index(op.f('ix_auth_logs_user_id'), table_name='auth_logs')
    op.drop_index(op.f('ix_auth_logs_timestamp'), table_name='auth_logs')
    op.drop_table('auth_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rate_cards_key_name'), table_name='rate_cards')
    op.drop_table('rate_cards')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
