"""add_unique_run_name_constraint

Revision ID: ab2f58beff51
Revises: d0ad8b7dd639
Create Date: 2026-04-29 00:00:22.274220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2f58beff51'
down_revision: Union[str, None] = 'd0ad8b7dd639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_run_team_name', 'runs', ['team_id', 'name'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_run_team_name', table_name='runs', postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###
