"""Add Audit reasoning and TestRun states

Revision ID: aee5de350a60
Revises: c3931377d591
Create Date: 2026-04-15 02:02:30.021400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee5de350a60'
down_revision: Union[str, None] = 'c3931377d591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('change_reason', sa.String(), nullable=True, comment='Mandatory comment for modifications'))
    op.add_column('test_runs', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('test_runs', sa.Column('end_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_test_runs_end_date'), 'test_runs', ['end_date'], unique=False)
    op.create_index(op.f('ix_test_runs_status'), 'test_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_runs_status'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_end_date'), table_name='test_runs')
    op.drop_column('test_runs', 'end_date')
    op.drop_column('test_runs', 'status')
    op.drop_column('audit_logs', 'change_reason')
    # ### end Alembic commands ###
