"""Add 4 new hourly rate overrides

Revision ID: c8c553c2733b
Revises: e0e64e9f1203
Create Date: 2026-05-10 14:33:59.368026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8c553c2733b'
down_revision: Union[str, None] = 'e0e64e9f1203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('sqpm_boise_hourly_rate_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('pl_hourly_rate_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('per_wqe_hourly_rate_override', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('lab_tech_manager_hourly_rate_override', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'lab_tech_manager_hourly_rate_override')
    op.drop_column('budgets', 'per_wqe_hourly_rate_override')
    op.drop_column('budgets', 'pl_hourly_rate_override')
    op.drop_column('budgets', 'sqpm_boise_hourly_rate_override')
    # ### end Alembic commands ###
