"""add_unique_run_name_and_auth_log_username_and_creator_names

Revision ID: d0ad8b7dd639
Revises: 533110036423
Create Date: 2026-04-28 23:59:26.311386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ad8b7dd639'
down_revision: Union[str, None] = '533110036423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_logs', sa.Column('username', sa.String(length=64), nullable=True, comment='Denormalized username for quick log readability'))
    op.add_column('budgets', sa.Column('created_by_name', sa.String(length=64), nullable=True))
    op.add_column('budgets', sa.Column('updated_by_name', sa.String(length=64), nullable=True))
    op.add_column('business_units', sa.Column('created_by_name', sa.String(length=64), nullable=True))
    op.add_column('business_units', sa.Column('updated_by_name', sa.String(length=64), nullable=True))
    op.add_column('families', sa.Column('created_by_name', sa.String(length=64), nullable=True))
    op.add_column('families', sa.Column('updated_by_name', sa.String(length=64), nullable=True))
    op.add_column('runs', sa.Column('created_by_name', sa.String(length=64), nullable=True))
    op.add_column('runs', sa.Column('updated_by_name', sa.String(length=64), nullable=True))
    op.add_column('teams', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('teams', sa.Column('created_by_name', sa.String(length=64), nullable=True))
    op.add_column('teams', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('teams', sa.Column('updated_by_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'updated_by_name')
    op.drop_column('teams', 'updated_at')
    op.drop_column('teams', 'created_by_name')
    op.drop_column('teams', 'created_at')
    op.drop_column('runs', 'updated_by_name')
    op.drop_column('runs', 'created_by_name')
    op.drop_column('families', 'updated_by_name')
    op.drop_column('families', 'created_by_name')
    op.drop_column('business_units', 'updated_by_name')
    op.drop_column('business_units', 'created_by_name')
    op.drop_column('budgets', 'updated_by_name')
    op.drop_column('budgets', 'created_by_name')
    op.drop_column('auth_logs', 'username')
    # ### end Alembic commands ###
