"""Add start and end dates to budgets

Revision ID: d1e2f3a4b5c6
Revises: c8c553c2733b
Create Date: 2026-05-10 19:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e2f3a4b5c6'
down_revision: Union[str, None] = 'c8c553c2733b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('budgets', sa.Column('end_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_budgets_end_date'), 'budgets', ['end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budgets_end_date'), table_name='budgets')
    op.drop_column('budgets', 'end_date')
    op.drop_column('budgets', 'start_date')
    # ### end Alembic commands ###
