"""drop_absolute_budget_unique_add_partial_index

Revision ID: e0e64e9f1203
Revises: 97041e9fa1a0
Create Date: 2026-05-09 22:13:20.366920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e64e9f1203'
down_revision: Union[str, None] = '97041e9fa1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_budgets_run_id', table_name='budgets')
    op.create_index(op.f('ix_budgets_run_id'), 'budgets', ['run_id'], unique=False)
    op.create_index('uq_budget_run_id_active', 'budgets', ['run_id'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_budget_run_id_active', table_name='budgets', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_budgets_run_id'), table_name='budgets')
    op.create_index('ix_budgets_run_id', 'budgets', ['run_id'], unique=True)
    # ### end Alembic commands ###
